### ISSUE TITLE
ABM Productos

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#1]
código
nombre
descripción
detalle
precio
referencia (gramaje, cm3, cantidad de unidades)
disponible/no disponible
publicado/no publicado
categorías

**Comment by luispablo** [comment]
¡Listo!

**Comment by lastresdiosas** [comment]
Acá podrías agregar la categoría (como combo)? así cuando doy de alta un producto puedo asociarlo.
Faltaría agregar la Marca del producto.

Acá se puede habilitar la carga de una imágen?

**Comment by luispablo** [comment]
Listo. **Y dejá de reabrir este ticket**.
