### ISSUE TITLE
Armado de la Home

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#13]
Header dividido en 2 partes: (en el de Guatemala lo diferencian los colores)
       1 - Home/ Zonas de Delivery (no sé como llamarle al mapa con el alcance)/Nosotros/ Contacto(#16)/  
       2 - Mi Cuenta (#18)/Mi Carrito(#17)/Login y Registro (#25)

Cuerpo:  dividido en 3 partes - 
       1 - columna izquierda: Catálogo (esta columna no desaparece NUNCA) (#14)
       2 - columna central: Espacio para mostrar los productos tipo ofertas o destacados (#27)
       3 - columna derecha: Preview del carrito y abajo algún banner o alguna propaganda nuestra  (esta columna no desaparece NUNCA) (#28)

Arriba o abajo del catálogo (donde quede mejor) podemos agregar un buscador por palabras (en otro isuue lo definimos mejor)

Arriba del header a la derecha o en la columna de la derecha (bien visibles) accesos a facebook, twitter (si decidimos ponerlo), dirección de mail de contacto (como para hacerlo más visible)

**Comment by luispablo** [comment]
Listo.
