### ISSUE TITLE
Mejoras al "panel de control"

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#135]
- Ver si se puede poner un checkbox al lado de cada dirección y de cada venta a entregar y un botón de validación general para cada caso, eso mejoraría los tiempos sino, cada vez que valido algo, refresca la página.
- IDEM para inválido

**Comment by luispablo** [comment]
No te voy a poner checkboxes. Pero te lo hice AJAX y le agreguè efectos lindos. Que lo disfrutes.
