### ISSUE TITLE
Muestra Categorias NO publicadas

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#140]
a Bebés y Adultos les puse"no publicadas", pero sigo viéndolas en el árbol de categorías. (Bebés tiene productos asociados, si despublico esa, debería traer todos la categoría madre, verdad?)

**Comment by luispablo** [comment]
Las categorías madres no se mostraban, pero las hijas si. Arreglé eso.
En cuanto a los productos, calculo que deberían mostrarse en la madre, pero no estaría nada mal que lo verificases.
