### ISSUE TITLE
Error en detalle de compra

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#163]
Una única compra (la del 28/6) se me rompe al querer entrar en el detalle. A la edición se puede entrar sin problemas, pero cuando ponés grabar para ver el detalle, aparece el mismo error

NoMethodError in Compras#show

**Comment by luispablo** [comment]
Te paso este issue así arreglamos la base para que te quede bien esa compra.

**Comment by lastresdiosas** [comment]
Ya arregle la compra que había quedado toda rota, pero me da un error al querer eliminar ítem roto (ID 27 que me ponés que ya no existe)
te subo tkt x esto.
