### ISSUE TITLE
Corregir registro

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#167]
- Igual que desde el admin, se rompe al querer agregar un regisrto a la base
- Completa por default un mail en el campo donde va el teléfono laboral.
- Dejar obligatorio sólo el teléfono de línea
- Corregir mensaje en inglés "Las contraseñas no coinciden" en vez de  "doesn't match confirmation" para la contraseña

**Comment by luispablo** [comment]
La rotura era tema de base, ya arreglado.
El mensaje te lo da en inglès porque tenés configurado el browser en inglés.
