### ISSUE TITLE
Armado sección Carrito de Compras

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#17]
Una línea por producto con: 
1 - foto miniatura (que linkea a "detalle del producto" (#29) )
2 - marca/nombre/descripción (unidos) (que linkea a "detalle del producto" (#29) )
3 - referencia 
4 - precio (unit)
5 - cantidad (editable y actualiza $total del producto)
6 - Total x producto
7 - Eliminar
Total de la compra
Costo de envío (0 si la compra es > $150, sino $15)

Total a pagar

Combo "Usar vale de descuento" que traiga los montos de vales disponibles 
Botón "Siguiente" a  seleccionar "dirección de entrega" (la primer dirección ingresada por el cliente queda como default u ordenar alfabéticamente el combo y que quede la primera) (#23)
Botón "Seguir comprando" para volver atrás a elegir más productos

**Comment by luispablo** [comment]
Listo el carrito en general, sigo con los issues particulares.
