### ISSUE TITLE
#18 - Mi historial de pedidos

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#19]
1 - Fecha
2 - Monto total de la compra
3 - Dirección de envío

Desde la línea linkear al detalle del pedido o agregar un botón que sea "ver detalle" con el mismo formato que el detalle de Mi Carrito (la opción del botón me parece más usable) (#29)

**Comment by luispablo** [comment]
Cómo ver el detalle de cada pedido lo dejo para un issue futuro así cierro éste ahora.
