### ISSUE TITLE
#18 - Mis datos personales

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#20]
Formulario con:"
"Datos personales"
1 - Nombre*
2 - Apellido*
3 - email*
4 - sexo
(Se debe proporcionar al menos un teléfono válido)
5 - tel particular
6 - tel celular
7 - tel laboral
Botones para:
"Cambiar de contraseña" (mail, pass vieja, pass nueva)
"Agregar hijo" (nombre, sexo, fecha de nacimiento, usa pañales?)

**Comment by luispablo** [comment]
Listo.
