### ISSUE TITLE
Verificación sitio (Añadir Proveedor) 

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#222]
Añade el registro TXT que aparece a continuación a la configuración de DNS de panaleradigital.com.ar.

```
google-site-verification=4kGqwfF7q5XuMganBRKIjI1CDr8Hs3JpLGAIOfJa5ro
```

**Comment by luispablo** [comment]
Pasame de dónde sacaste ésto a ver si puedo hacerlo.

**Comment by lastresdiosas** [comment]
Hay algo acá, pero una explicación mejor en otro lado, si la encuentro te la paso.
https://support.google.com/webmasters/bin/answer.py?hl=en&answer=176792&topic=2370564&ctx=topic
