### ISSUE TITLE
Informar Win Live

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#226]
http://www.bing.com/toolbox/webmaster/

Poner en el raiz el BingSiteAuth.xml que lo tenés en dropbox y comprobar que este bien cargado entrando aca:
http://panaleradigital.com.ar/BingSiteAuth.xml "comprobar"

`<meta name="msvalidate.01" content="1D3F689785A24B58AD77E9B9D37CF627" />`

**Comment by luispablo** [comment]
Todo esto ya lo hice.
