### ISSUE TITLE
Validación Win Live (BingSiteAuth.xml)

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#228]
Lo tenés en la misma carpeta de posicionamiento web, encajalo donde pusiste el de google. (el raiz)

Después entrar a http://www.pañaleradigital.com.ar/BingSiteAuth.xml y poner VERIFICAR (si por un tema de autenticación o algo de eso me reclama a mi, pasame el tkt que lo termino yo)

**Comment by luispablo** [comment]
Esto también está hecho.
