### ISSUE TITLE
#17 - Seleccionar dirección de entrega

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#23]
Combo con los nombres de las direcciones, al cambiar el nombre en el combo, se ve en pantalla la dirección que representa.
Botones "Actualizar" y "Agregar dirección"
Cuadro de texto para escribir hasta 30 caracteres por si se quiere aclarar algo.

Check para Condiciones de la venta con un link para que se puedan leer (tipo modal) (#24)
(No se puede hacer seguir sin este check)

**Comment by luispablo** [comment]
Listo.
