### ISSUE TITLE
#25 - Registro de usuarios

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#26]
Solicitar datos personales.

Formulario con:"
"Datos personales"
1 - Nombre*
2 - Apellido*
3 - email*
4 - sexo
(Se debe proporcionar al menos un teléfono válido)
5 - tel particular
6 - tel celular
7 - tel laboral

"Sus Hijos"
Botón "Agregar hijo" (nombre, sexo, fecha de nacimiento, usa pañales?)

**Comment by luispablo** [comment]
Terminado.
