### ISSUE TITLE
Aviso publicitario PuertaxPuerta

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#262]
Número 3. $160. Tipo vale de descuento.

8,55x2,7 Apaisado.  
- Logo y nombre chiquito negro
- Slogan: "Los mejores precios sin moverte de tu casa"
- Descuento 10% grande y rojo
- Código del vale.
- URL visible en negritas.
- Aviso chiquito "sólo hasta fin de mes" o "válido para las primeras 100 compras"
- Recuadro en rojo gruesito?
- Probemos puntas redondeadas y angulares para comparar

**Comment by luispablo** [comment]
Subido a Dropbox.
