### ISSUE TITLE
Luego de crear el tkt #265 se rompió el admin.

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#266]
Después de la inconsistencia del tkt #265, no puedo entrar más al panel de control del admin. "We're sorry, but something went wrong."
Fui a las ventas...y se habían generado 2 ventas. 
- Una con el importe total de la compra (lo comprado inicialmente + lo agregado al carrito a último momento)
- La otra con importe 0 y sin detalles más que mi nombre en el usuario.
  Borré las 2 y pude volver al panel de control
  <br/><br/>
  **ESTO PASA SOLAMENTE SI CARGO UN VALE DE DESCUENTO. Si no cargo Vale, no refresca la página de confirmación pero no rompe el admin.**

**Comment by luispablo** [comment]
No podemos reproducirlo.
