### ISSUE TITLE
El vale deja de servir en cuanto se usa 

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#268]
Eso está bien así? En cuanto se confirma la compra desde la parte pública el flag del vale cambia a TRUE.
Suponete que yo anulo por algo la compra desde el admin, Ese vale usado YA NO SIRVE, lo dejamos así, no? o hay algo que no estamos contemplando? Llegado el caso le damos otro vale a la persona, no?

**Comment by luispablo** [comment]
Esta pregunta cambia ahora que los vales valen varias veces.
