### ISSUE TITLE
Llenado Home (columna central)

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#27]
8 o 9 imágenes de productos. 
Desde  cada uno:
1- foto
2 - boton "detalle"
3 - boton "agregar al carrito" - cuando se agrega al carrito hay que actualizar:
- "Mi Carrito" 
- la columna de la izquierda con la preview 
- la cantidad de productos seleccionados en total en la preview

**Comment by luispablo** [comment]
Terminado.
