### ISSUE TITLE
Llenado de la preview (columna der)

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#28]
1 - Cantidad de productos x Marca/Producto...precio total  y botón o ícono para eliminar(una línea por producto que en total muestra el nombre con no más de 10 caracteres en letra chiquita) que se vea el nombre completo con un ALT
2 - Delivery
3 - Total
4 - Botón a "mi carrito"
Ejemplo:

3xHuggies...      $120 [tachito]
1xPamp...            $45 [tachito]

Delivery                $0
Total                  $165

(no me toma los espacio y queda todo desordenado el ejemplito pero vos sos creativo)
Debajo del botón del carrito de compras podría agregarse la cantidad de productos que lleva agregados al carrito.

**Comment by luispablo** [comment]
Terminado.
