### ISSUE TITLE
Alta de una compra

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#30]
Formulario con:
- Fecha (actual por default)
- Combo con códigos de productos
- Cantidad comprada

Cada fila puede editarse y eliminarse.
Cada vez que se graba una compra se actualiza el Stock de los productos afectados.

**Comment by luispablo** [comment]
Por ahora muestro el total comprado. Cuando tengamos las confirmaciones y el circuito de las compras resuelto pongo el stock.
