### ISSUE TITLE
Pantalla de error al editar Vale

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#306]
No puedo editar un vale desde el botón "editar"
Tampoco puedo hacerlo haciendo clic en sobre la descripción. Aclaro que eso me pasa cuando la descripción está vacía.  Tal vez tendrías que dejarme una rallita por default para cuando yo borro todo, o sea, que nunca quede vacío por mas que yo borre el contenido.

**Comment by luispablo** [comment]
Tampoco puedo reproducirlo.

**Comment by lastresdiosas** [comment]
solo tarda mucho la carga.
