### ISSUE TITLE
Alta de una venta

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#31]
Cuando un usuario completa una compra (venta para nosotros) debe quedar dicha venta "pendiente de confirmación":
- Se envía por mail con un acceso al "Confirmar" del Administrador, en caso de nuevo usuario o nueva dirección de un usuario existente (para comprobar radio de cobertura)
- Se accede a una bandeja de entrada del administrador donde están las ventas pendientes de confirmación. 

La bandeja de entrada tiene las siguientes columnas:
1 - Usuario
2 - Cantidad de productos
3 - Monto total 
4 - Detalle de la venta (#32) link al detalle en formato no editable
5 - Botones "Actualizar" (por si se modificó algo de la venta entre la compra online y el delivery, link al detalle editable) y "Borrar"

**Comment by luispablo** [comment]
Terminado.
