### ISSUE TITLE
Selección de una categoría

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#36]
Cuando desde el catálogo se selecciona una categoría, tiene que desplegar todos los productos que tenga asociados.
Entonces...para mostrar esos productos:
- Listarlos UNO por línea con foto, nombre/descripción/referencia/precio 
- botones ver detalles/agregar al carrito
  O:
  -listar como en destacados...VARIOS por línea.

En todos los casos permitir ordenamiento (#37)

**Comment by luispablo** [comment]
Terminado.
