### ISSUE TITLE
Modificar "detalle del producto"

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#46]
- No dejar visible el código de producto.
- Acomodar estos campos para que queden en el título así: "Nombre - Descripción"
- Acomodar a la derecha de la imagen lo importante  "Nombre - Descripción" y debajo talle, unidades y precio, el campito cantidad (editable) y el botón para agregar al carrito. Abaj,o el Detalle, si es que lo tuviera.

**Comment by luispablo** [comment]
Ya arreglé el detalle en otro issue. De ser necesario, crear uno nuevo.
