### ISSUE TITLE
Alta de cualquier ítem

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#52]
Cuando terminás de dar de alta un ítem (producto, categoría, etc) y grabás, te queda un resumen del alta, con botones "editar" y "volver"  Si se puede agregar un "nuevo" para no tener que volver para agregar otro ítem al mismo listado.

**Comment by luispablo** [comment]
En categorías, productos, marcas, vales y compras.

**Comment by luispablo** [comment]
Terminado.
