### ISSUE TITLE
Envio de mail al realizar una compra

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#53]
Enviar mail cuando el usuario termina una compra.

Estimado nombre apellido, gracias por haber comprado en Pañalera Digital.

Detalle de su pedido:  (idem resumen web previo a la venta)
Forma de pago: contra entrega
Dirección de entrega: 

---

Las pañaleras estas automáticas ponen:
"Puedes revisar tu pedido y descargar la factura aquí: "Historial de Pedidos" dentro de tu cuenta "Entrar en Mi Cuenta" de nuestro sitio web."
Además envian en PDF la "factura"

**Comment by luispablo** [comment]
Ya estaba hecho...
