### ISSUE TITLE
Mejorar leyenda página de despedida

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#59]
Felicitaciones! Recibirás un mail con el detalle de tu compra.
IMPORTANTE:Como es la primera vez que comprás, estaremos llamándote por teléfono para confirmar tus datos.

Felicitaciones! Recibirás un mail con el detalle de tu compra.  (cartel a partir de la segunda compra en adelante)

(ALGO ASI, DESPUES LO MEJORAMOS)

**Comment by luispablo** [comment]
Listo.
