### ISSUE TITLE
Corregir compra

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#85]
- Combo ordenado alfabéticamente por Nombre
- Agreguemos al final del combo [xRef] serían los 3 primeros caracteres del campo Referencia
- Al agregar un producto, me redondea los precios del resto de las cosas que ya cargué (que me permita decimales sin redondeo)
- Sacar el decimal del campo Cantidad
- Si se puede, cuando tabulo, que salte del campo cantidad al precio y que NO VAYA al "quitar" (porque saco los productos por error)
- Si no es mucho pedir, el combo podría mostrármelo en cada línea que se agrega (tipo el sistema de federico que cuando tabulas, bajás a la línea siguiente y te deja elegir del combo en la misma línea) 
- Sacar el botón NUEVO que a menos que agregue una línea nueva, no sirve.

**Comment by luispablo** [comment]
Algunos arreglos quedan para más adelante porque llevan demasiado trabajo para algo que no ve el público.
