### ISSUE TITLE
Editar encabezado de una venta

### ISSUE THREAD

**Issue by lastresdiosas** [luispablo/panialera#87]
- Hoy no puedo editarlo. 
- Necesitaría tener un campo para texto libre (para agregr, suponete, lo compró Ainara)
- Un campo con el total ingresado por la venta (delivery+venta)
- Tratar de poner las fehcas con un datepicker que es una recagada poner campito por campito.

**Comment by luispablo** [comment]
Lo único que no te hago de esto es el datepicker, ahora, por el tiempo que insumiría.
